/* ---------- recipes (für 2 Personen, Cosori höchstens 200 °C, Thermomix TM5/TM6/TM7) ---------- */
const I = (q, u, n, s, o) => Object.assign({ q, u, n, s }, o || {});
const P = (q, u, n, o) => Object.assign({ q, u, n, s: 'gewuerz', p: 1 }, o || {});
const A = (label, c, m, sh, pre) => ({ label, c, m, sh: sh || null, pre: !!pre });
// Thermomix: Dauer in Sekunden, °C oder 'varoma' (null = ohne Hitze), Stufe (Zahl, 'sanft', 'knet', 'turbo'), Linkslauf
const TMX = (label, sec, temp, speed, rev) => ({ tm: { label, sec, temp: temp || null, speed, rev: !!rev } });
const MIN = 60;

const BUILTIN = [
  { id: 'joghurt', t: 'Joghurt', pen: 'marker', cat: 'fruehstueck', name: 'Joghurt mit Obst & Knuspermüsli', time: 15,
    ing: [
      I(400, 'g', 'Naturjoghurt', 'kuehl', { x: 'oder griechischer Joghurt' }),
      I(1, '', 'Banane', 'obst', { pl: 'Bananen' }),
      I(125, 'g', 'Beeren', 'obst', { x: 'frisch oder TK' }),
      I(100, 'g', 'Haferflocken', 'trocken', { x: 'gern kernige' }),
      I(30, 'g', 'Haselnüsse', 'backen', { x: 'oder Mandeln' }),
      P(2, 'EL', 'Honig', { s: 'backen' }),
      P(1, 'EL', 'Rapsöl'),
      P(1, 'Prise', 'Zimt'),
    ],
    steps: [
      [TMX('Nüsse hacken', 3, null, 5), 'Für das Knuspermüsli die Haselnüsse in den Mixtopf geben und grob hacken.'],
      [TMX('Müsli mischen', 20, null, 2, true), 'Haferflocken, 1 EL Honig, Öl und Zimt zugeben und vermischen. Klebt Honig am Rand, mit dem Spatel nach unten schieben und kurz wiederholen.'],
      [A('Knuspermüsli rösten', 150, 10, 5), 'Ein passend zugeschnittenes Backpapier in den Korb legen, die Mischung flach darauf verteilen und rösten. Nach 5 Min umrühren, damit nichts zu dunkel wird.'],
      'Auf einem Teller vollständig abkühlen lassen – erst dann wird das Müsli richtig knusprig.',
      'Joghurt auf zwei Schalen verteilen. Banane in Scheiben schneiden und mit den Beeren darauf geben.',
      'Mit dem restlichen Honig beträufeln und 2–3 EL Knuspermüsli darüberstreuen.',
    ],
    tip: 'Das Knuspermüsli hält sich im Schraubglas gut zwei Wochen – am besten gleich die doppelte Menge rösten.' },

  { id: 'bircher', t: 'Bircher', pen: 'caps', cat: 'fruehstueck', name: 'Bircher-Müsli mit gerösteten Nüssen', time: 10,
    ing: [
      I(80, 'g', 'Haferflocken', 'trocken', { x: 'zarte' }),
      I(150, 'ml', 'Milch', 'kuehl'),
      I(150, 'g', 'Naturjoghurt', 'kuehl'),
      I(1, '', 'Apfel', 'obst', { pl: 'Äpfel' }),
      I(0.5, '', 'Zitrone', 'obst', { pl: 'Zitronen', x: 'Saft' }),
      I(100, 'g', 'Beeren', 'obst', { x: 'frisch oder TK' }),
      I(30, 'g', 'Haselnüsse', 'backen', { x: 'oder Mandeln' }),
      P(1, 'EL', 'Honig', { s: 'backen' }),
    ],
    steps: [
      'Am Vorabend Haferflocken mit Milch und Joghurt verrühren und abgedeckt über Nacht in den Kühlschrank stellen.',
      [A('Nüsse rösten', 160, 4, 2), 'Die Nüsse in einer kleinen ofenfesten Form in den Korb stellen und rösten, nach 2 Min schütteln. Danach grob hacken.'],
      [TMX('Apfel zerkleinern', 4, null, 4), 'Morgens den Apfel vierteln, entkernen und mit Schale und dem Zitronensaft in den Mixtopf geben. Grob zerkleinern – der Zitronensaft hält ihn hell.'],
      [TMX('Unterrühren', 15, null, 2, true), 'Die eingeweichten Flocken und den Honig zugeben und unterrühren. Ist das Müsli zu fest, einen Schuss Milch dazugeben.'],
      'In Schalen füllen und mit Beeren und gerösteten Nüssen bestreuen.',
    ],
    tip: 'Die Nüsse gleich für mehrere Tage rösten – im Glas bleiben sie eine Woche knackig.' },

  { id: 'porridge', t: 'Porridge', pen: 'marker', cat: 'fruehstueck', name: 'Porridge mit Zimtäpfeln aus dem Cosori', time: 15,
    ing: [
      I(80, 'g', 'Haferflocken', 'trocken', { x: 'zarte' }),
      I(400, 'ml', 'Milch', 'kuehl', { x: 'oder Haferdrink' }),
      I(1, '', 'Apfel', 'obst', { pl: 'Äpfel' }),
      I(2, 'EL', 'Walnusskerne', 'backen'),
      P(1, 'EL', 'Butter', { s: 'kuehl' }),
      P(1, 'TL', 'Zimt'),
      P(2, 'TL', 'Honig', { s: 'backen', x: 'oder Ahornsirup' }),
      P(1, 'Prise', 'Salz'),
    ],
    steps: [
      'Apfel vierteln, entkernen und in Spalten schneiden. Mit geschmolzener Butter, Zimt und 1 TL Honig mischen.',
      [A('Zimtäpfel garen', 180, 8, 4), 'Apfelspalten im Korb garen, nach 4 Min schütteln, bis sie weich und leicht karamellisiert sind.'],
      [TMX('Porridge kochen', 12 * MIN, 90, 2, true), 'Währenddessen Haferflocken, Milch und eine Prise Salz in den Mixtopf geben und cremig kochen. Wer ihn dicker mag, gibt 1–2 Min dazu.'],
      'Porridge in Schalen füllen, Zimtäpfel und gehackte Walnüsse darauf geben und mit dem restlichen Honig beträufeln.',
    ],
    tip: 'Im Herbst schmecken auch Birnen oder Zwetschgen – gleiche Zeit im Cosori.' },

  { id: 'linsen', t: 'Linsen mit Spätzle', pen: 'caps', cat: 'haupt', name: 'Linsen mit Spätzle & Saitenwürstle', time: 50,
    ing: [
      I(150, 'g', 'Tellerlinsen', 'trocken', { x: 'braune Linsen' }),
      I(2, '', 'Zwiebel', 'obst', { pl: 'Zwiebeln', x: 'eine davon für Röstzwiebeln' }),
      I(1, 'Bund', 'Suppengrün', 'obst', { x: 'Karotte, Sellerie, Lauch' }),
      I(250, 'g', 'frische Spätzle', 'kuehl', { x: 'aus dem Kühlregal' }),
      I(4, '', 'Saitenwürstle', 'fleisch', { x: 'Wiener Würstchen' }),
      P(600, 'ml', 'Gemüsebrühe'),
      P(3, 'EL', 'Essig', { x: 'Rotwein- oder Balsamicoessig' }),
      P(2, 'EL', 'Rapsöl'),
      P(1, 'EL', 'Mehl', { s: 'backen' }),
      P(1, '', 'Lorbeerblatt', { pl: 'Lorbeerblätter' }),
      P(1, 'TL', 'Senf'),
      P(1, 'EL', 'Butter', { s: 'kuehl' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Linsen in einem Sieb abspülen. Eine Zwiebel halbieren, Karotte und Sellerie aus dem Suppengrün in grobe Stücke schneiden (den Lauch für eine Suppe aufheben).',
      [TMX('Gemüse zerkleinern', 5, null, 5), 'Zwiebel, Karotte und Sellerie in den Mixtopf geben und zerkleinern. Mit dem Spatel nach unten schieben.'],
      [TMX('Andünsten', 3 * MIN, 120, 1), '1 EL Öl zugeben und das Gemüse andünsten.'],
      [TMX('Mehl anschwitzen', 1 * MIN, 100, 1), '2 TL Mehl darüberstäuben und kurz anschwitzen.'],
      [TMX('Linsen garen', 35 * MIN, 100, 'sanft', true), 'Brühe, Linsen und Lorbeerblatt zugeben und weich garen. Das Garkörbchen statt des Messbechers auf den Deckel stellen, dann kann Dampf entweichen. Erst salzen, wenn die Linsen weich sind.'],
      [A('Röstzwiebeln', 170, 10, [3, 6]), 'Für die Röstzwiebeln die zweite Zwiebel in feine Ringe schneiden, mit 1 TL Mehl und 1 EL Öl vermengen und im Cosori knusprig rösten. Alle 3 Min schütteln und am Ende gut aufpassen – sie werden schnell zu dunkel.'],
      'Die Saitenwürstle in den letzten 5 Min in einem Topf mit heißem, nicht mehr kochendem Wasser ziehen lassen – sonst platzen sie.',
      'Spätzle in einer Pfanne in der Butter schwenken und erwärmen.',
      [TMX('Abschmecken', 30, null, 'sanft', true), 'Das Lorbeerblatt herausnehmen. Essig, Senf, Salz und Pfeffer zugeben, unterrühren und die Linsen kräftig süß-sauer abschmecken. Mit Spätzle, Würstle und Röstzwiebeln servieren.'],
    ],
    tip: 'Ganz schwäbisch kommt der Essig erst zum Schluss – die Linsen dürfen ruhig deutlich säuerlich schmecken.' },

  { id: 'tikka', t: 'Tikka Masala', pen: 'script', cat: 'haupt', name: 'Chicken Tikka Masala mit Basmatireis', time: 45,
    ing: [
      I(400, 'g', 'Hähnchenbrustfilet', 'fleisch', { x: 'oder Hähnchenschenkel ohne Knochen' }),
      I(150, 'g', 'Naturjoghurt', 'kuehl'),
      I(0.5, '', 'Zitrone', 'obst', { pl: 'Zitronen' }),
      I(2, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(1, 'Stück', 'Ingwer', 'obst', { x: 'ca. 3 cm' }),
      I(1, '', 'Zwiebel', 'obst', { pl: 'Zwiebeln' }),
      I(1, 'Bund', 'Koriander', 'obst', { x: 'oder Petersilie' }),
      I(1, 'Dose', 'stückige Tomaten', 'konserve', { x: '400 g' }),
      I(1, 'EL', 'Tomatenmark', 'konserve'),
      I(100, 'ml', 'Sahne', 'kuehl'),
      I(150, 'g', 'Basmatireis', 'trocken'),
      I(2, 'TL', 'Garam Masala', 'gewuerz'),
      I(1, 'TL', 'Kurkuma', 'gewuerz'),
      P(1, 'TL', 'Paprikapulver'),
      P(1, 'EL', 'Rapsöl'),
      P(null, '', 'Salz & Chiliflocken'),
    ],
    steps: [
      'Hähnchen in mundgerechte Stücke schneiden. Knoblauch und Ingwer schälen und die Hälfte davon für die Marinade fein reiben.',
      'Den geriebenen Knoblauch und Ingwer mit 100 g Joghurt, dem Saft der halben Zitrone, 1 TL Garam Masala, Kurkuma, Paprikapulver und ½ TL Salz verrühren. Das Fleisch darin mindestens 30 Min marinieren, gern auch über Nacht.',
      [A('Hähnchen grillen', 200, 12, 6, true), 'Cosori vorheizen. Die Hähnchenstücke mit etwas Abstand in den Korb legen (überschüssige Marinade abstreifen) und garen, nach 6 Min wenden. Leicht dunkle Ränder sind gewollt – das ist das „Tikka“. Innen darf nichts mehr rosa sein.'],
      'Währenddessen den Reis nach Packungsanleitung kochen.',
      [TMX('Zerkleinern', 5, null, 5), 'Für die Sauce die Zwiebel halbieren und mit dem restlichen Knoblauch und Ingwer in den Mixtopf geben. Zerkleinern und mit dem Spatel nach unten schieben.'],
      [TMX('Andünsten', 4 * MIN, 120, 1), 'Öl, Tomatenmark und 1 TL Garam Masala zugeben und andünsten.'],
      [TMX('Sauce köcheln', 10 * MIN, 100, 1), 'Tomaten zugeben und sämig köcheln. Das Garkörbchen statt des Messbechers auf den Deckel stellen.'],
      [TMX('Pürieren', 20, null, 6), 'Sahne und den restlichen Joghurt zugeben und die Sauce mit eingesetztem Messbecher fein pürieren. Mit Salz und Chili abschmecken.'],
      [TMX('Ziehen lassen', 2 * MIN, 90, 'sanft', true), 'Das Hähnchen in die Sauce geben und darin heiß werden lassen. Mit Reis und gehacktem Koriander servieren.'],
    ],
    tip: 'Vegetarisch: Statt Hähnchen einen kleinen Blumenkohl in Röschen und 1 Dose Kichererbsen marinieren und im Cosori bei 200 °C etwa 15 Min rösten.' },

  { id: 'asianudeln', t: 'Gebratene Asia-Nudeln', pen: 'script', cat: 'haupt', name: 'Gebratene Asia-Nudeln mit Knusper-Tofu', time: 35,
    ing: [
      I(200, 'g', 'Tofu natur', 'kuehl', { x: 'fest' }),
      I(200, 'g', 'Mie-Nudeln', 'trocken', { x: 'oder Udon' }),
      I(1, '', 'rote Paprika', 'obst', { pl: 'rote Paprika' }),
      I(1, '', 'Karotte', 'obst', { pl: 'Karotten' }),
      I(1, '', 'Pak Choi', 'obst', { x: 'oder 150 g Brokkoli' }),
      I(2, '', 'Frühlingszwiebel', 'obst', { pl: 'Frühlingszwiebeln' }),
      I(1, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(1, 'Stück', 'Ingwer', 'obst', { x: 'ca. 2 cm' }),
      I(4, 'EL', 'Sojasauce', 'konserve'),
      I(1, 'EL', 'Austernsauce', 'konserve', { x: 'oder Hoisinsauce' }),
      I(1, 'TL', 'Sesamöl', 'gewuerz'),
      I(1, 'EL', 'Sesam', 'backen'),
      I(1, 'EL', 'Speisestärke', 'backen'),
      P(2, 'EL', 'Rapsöl'),
      P(1, 'TL', 'Zucker', { s: 'backen' }),
    ],
    steps: [
      'Tofu gut trocken tupfen (am besten 10 Min zwischen Küchenpapier pressen) und in 2-cm-Würfel schneiden. Mit 1 EL Sojasauce, 1 EL Öl und der Stärke vermengen.',
      [A('Tofu knusprig backen', 200, 15, 7), 'Tofu im Korb knusprig backen, nach 7 Min kräftig schütteln.'],
      'Nudeln nach Packungsanleitung garen, abgießen, kalt abschrecken und mit dem Sesamöl mischen, damit sie nicht kleben.',
      'Paprika und Karotte in feine Streifen, Pak Choi in Stücke und Frühlingszwiebeln in Ringe schneiden. Knoblauch und Ingwer fein hacken.',
      'Restliches Öl in einer großen Pfanne oder im Wok stark erhitzen. Karotte und Paprika 3 Min unter Rühren braten, dann Pak Choi, Knoblauch und Ingwer 1 Min mitbraten.',
      'Nudeln zugeben. Restliche Sojasauce, Austernsauce und Zucker verrühren, darübergießen und alles 2 Min kräftig durchbraten.',
      'Mit Knusper-Tofu, Frühlingszwiebeln und Sesam servieren. Wer mag, gibt etwas Chilisauce dazu.',
    ],
    tip: 'Statt Tofu gehen auch Hähnchenstreifen: mit Sojasauce und Stärke mischen und bei 200 °C etwa 10 Min garen.' },

  { id: 'bolo', t: 'Bolo', pen: 'caps', cat: 'haupt', name: 'Spaghetti Bolognese mit Knoblauchbrot', time: 60,
    ing: [
      I(250, 'g', 'Rinderhackfleisch', 'fleisch', { x: 'oder gemischtes Hack' }),
      I(1, '', 'Zwiebel', 'obst', { pl: 'Zwiebeln' }),
      I(1, '', 'Karotte', 'obst', { pl: 'Karotten' }),
      I(1, 'Stange', 'Staudensellerie', 'obst'),
      I(3, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(1, 'EL', 'Tomatenmark', 'konserve'),
      I(400, 'g', 'passierte Tomaten', 'konserve'),
      I(100, 'ml', 'Rotwein', 'getraenke', { x: 'oder Gemüsebrühe' }),
      I(250, 'g', 'Spaghetti', 'trocken'),
      I(40, 'g', 'Parmesan', 'kuehl'),
      I(0.5, '', 'Ciabatta', 'brot'),
      P(1, 'EL', 'Olivenöl'),
      P(2, 'EL', 'Butter', { s: 'kuehl', x: 'weich' }),
      P(1, 'TL', 'Oregano', { x: 'getrocknet' }),
      P(null, '', 'Salz, Pfeffer & 1 Prise Zucker'),
    ],
    steps: [
      [TMX('Gemüse zerkleinern', 5, null, 5), 'Zwiebel halbieren, Karotte und Sellerie in Stücke schneiden und mit 2 Knoblauchzehen in den Mixtopf geben. Zerkleinern und mit dem Spatel nach unten schieben.'],
      [TMX('Andünsten', 3 * MIN, 120, 1), 'Öl zugeben und das Gemüse andünsten.'],
      [TMX('Hack anbraten', 5 * MIN, 120, 1, true), 'Hackfleisch zugeben und krümelig anbraten.'],
      [TMX('Ablöschen', 3 * MIN, 120, 1, true), 'Tomatenmark und Rotwein zugeben und ohne Messbecher etwas einkochen lassen.'],
      [TMX('Sauce köcheln', 25 * MIN, 100, 1, true), 'Passierte Tomaten und Oregano zugeben, mit Salz, Pfeffer und einer Prise Zucker würzen und köcheln lassen. Das Garkörbchen statt des Messbechers auf den Deckel stellen. Länger köcheln schadet nicht.'],
      'Spaghetti in reichlich Salzwasser al dente kochen.',
      [A('Knoblauchbrot', 180, 5), 'Für das Knoblauchbrot die weiche Butter mit der letzten gepressten Knoblauchzehe und etwas Salz verrühren. Ciabatta in Scheiben schneiden, bestreichen und im Cosori goldbraun backen.'],
      'Spaghetti mit der Sauce mischen und mit frisch geriebenem Parmesan und dem Knoblauchbrot servieren.',
    ],
    tip: 'Die Sauce lohnt sich in doppelter Menge: Sie lässt sich portionsweise gut einfrieren. Noch kräftiger wird sie, wenn ihr das Hack vorher in der Pfanne scharf anbratet.' },

  { id: 'pizza', t: 'Pizza', sub: 'Salat', pen: 'caps', cat: 'haupt', name: 'Pizza aus dem Cosori mit grünem Salat', time: 30,
    ing: [
      I(1, 'Rolle', 'frischer Pizzateig', 'kuehl', { x: 'Kühlregal, ca. 400 g' }),
      I(150, 'g', 'passierte Tomaten', 'konserve', { x: 'oder Pizzasauce' }),
      I(1, 'Kugel', 'Mozzarella', 'kuehl', { x: '125 g' }),
      I(100, 'g', 'Champignons', 'obst', { x: 'oder Belag nach Wahl' }),
      I(1, 'Topf', 'Basilikum', 'obst'),
      I(1, '', 'Kopfsalat', 'obst', { pl: 'Kopfsalate', x: 'oder 100 g Rucola' }),
      I(0.5, '', 'Salatgurke', 'obst', { pl: 'Salatgurken' }),
      I(150, 'g', 'Kirschtomaten', 'obst'),
      P(3, 'EL', 'Olivenöl'),
      P(1, 'EL', 'Balsamico'),
      P(1, 'TL', 'Senf'),
      P(1, 'TL', 'Oregano', { x: 'getrocknet' }),
      P(null, '', 'Salz, Pfeffer & 1 Prise Zucker'),
    ],
    steps: [
      'Teig ausrollen und mit einem Teller als Schablone zwei Kreise ausschneiden, die in den Korb passen (etwa 20 cm).',
      'Jeden Teigkreis auf ein passend zugeschnittenes Stück Backpapier legen. Mit Tomatensauce bestreichen, mit Oregano würzen, Mozzarella zerzupfen und mit den Champignons darauf verteilen.',
      [A('Pizza backen (je Pizza)', 200, 9, 0, true), 'Cosori ohne Backpapier vorheizen. Dann die erste Pizza mit dem Backpapier in den Korb setzen und backen, bis der Rand goldbraun ist. Die zweite Pizza genauso.'],
      'Währenddessen Salat waschen und zupfen, Gurke in Scheiben schneiden und Tomaten halbieren.',
      'Für das Dressing 2 EL Olivenöl, Balsamico, Senf, Zucker, Salz und Pfeffer verrühren und erst kurz vor dem Servieren untermischen.',
      'Pizza mit frischem Basilikum und einem Spritzer Olivenöl servieren.',
    ],
    tip: 'Teig selbst machen mit dem Thermomix: 150 g Wasser, 10 g frische Hefe und 1 Prise Zucker 2 Min/37 °C/Stufe 2 verrühren, dann 250 g Mehl, ½ TL Salz und 1 EL Olivenöl 2 Min/Knetstufe kneten und abgedeckt 45 Min gehen lassen.' },

  { id: 'brotsalat', t: 'Brot-Salat', pen: 'marker', cat: 'leicht', name: 'Brotsalat (Panzanella)', time: 30,
    ing: [
      I(200, 'g', 'Ciabatta', 'brot', { x: 'gern vom Vortag' }),
      I(400, 'g', 'reife Tomaten', 'obst', { x: 'gemischt' }),
      I(0.5, '', 'Salatgurke', 'obst', { pl: 'Salatgurken' }),
      I(1, '', 'rote Zwiebel', 'obst', { pl: 'rote Zwiebeln' }),
      I(1, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(1, 'Topf', 'Basilikum', 'obst'),
      I(1, 'EL', 'Kapern', 'konserve'),
      P(4, 'EL', 'Olivenöl'),
      P(2, 'EL', 'Essig', { x: 'Rotwein- oder Balsamicoessig' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Brot in 2–3 cm große Würfel schneiden und mit 1 EL Olivenöl und einer Prise Salz mischen.',
      [A('Brotwürfel rösten', 180, 6, 3), 'Brotwürfel im Cosori goldbraun rösten, nach 3 Min schütteln.'],
      'Tomaten in mundgerechte Stücke schneiden, leicht salzen und in einem Sieb über einer Schüssel 10 Min abtropfen lassen. Den Saft auffangen.',
      'Gurke halbieren und in Scheiben schneiden, Zwiebel in feine Ringe schneiden und den Knoblauch fein hacken.',
      'Den aufgefangenen Tomatensaft mit Essig, Knoblauch, dem restlichen Olivenöl, Salz und Pfeffer verrühren.',
      'Brot, Tomaten, Gurke, Zwiebel und Kapern mit dem Dressing mischen und 10 Min durchziehen lassen, damit das Brot den Saft aufnimmt. Mit Basilikum servieren.',
    ],
    tip: 'Mit einer zerzupften Kugel Mozzarella oder etwas Feta wird daraus ein sättigendes Abendessen.' },

  { id: 'fisch', t: 'Fisch', pen: 'caps', cat: 'haupt', name: 'Lachs mit Ofenkartoffeln, Brokkoli & Dill-Dip', time: 40,
    ing: [
      I(2, '', 'Lachsfilet', 'fleisch', { pl: 'Lachsfilets', x: 'je ca. 140 g' }),
      I(500, 'g', 'kleine Kartoffeln', 'obst', { x: 'festkochend, z. B. Drillinge' }),
      I(1, '', 'Brokkoli', 'obst', { x: 'ca. 400 g' }),
      I(1, '', 'Zitrone', 'obst', { pl: 'Zitronen' }),
      I(1, 'Bund', 'Dill', 'obst'),
      I(150, 'g', 'griechischer Joghurt', 'kuehl'),
      P(2, 'EL', 'Olivenöl'),
      P(1, 'TL', 'Paprikapulver'),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Kartoffeln waschen, halbieren und mit 1 EL Öl, Paprikapulver und Salz mischen.',
      [A('Kartoffeln garen', 200, 15, 7), 'Kartoffeln im Cosori garen, nach 7 Min schütteln.'],
      'Brokkoli in Röschen teilen und mit 1 TL Öl und etwas Salz mischen.',
      [A('Brokkoli dazugeben', 200, 7), 'Brokkoli zu den Kartoffeln in den Korb geben, kurz durchschütteln und alles zusammen fertig garen. Dann herausnehmen und abgedeckt warm halten.'],
      'Lachs trocken tupfen, mit dem restlichen Öl bestreichen, salzen, pfeffern und mit 2 Zitronenscheiben belegen.',
      [A('Lachs garen', 180, 9), 'Lachs mit der Hautseite nach unten in den Korb legen und garen. Dicke Filets brauchen 10–12 Min – innen darf er noch leicht glasig sein.'],
      [TMX('Dill hacken', 3, null, 8), 'Für den Dip die Dillspitzen in den Mixtopf geben und fein hacken.'],
      [TMX('Dip verrühren', 10, null, 3), 'Joghurt, etwas Zitronenabrieb, Salz und Pfeffer zugeben und verrühren. Alles mit Zitronenspalten servieren.'],
    ],
    tip: 'Auch Kabeljau oder Seelachs gelingen so: 180 °C, je nach Dicke 8–10 Min.' },

  { id: 'ricotta', t: 'Ricotta Zucchini', pen: 'marker', cat: 'haupt', name: 'Gefüllte Zucchini mit Ricotta', time: 35,
    ing: [
      I(2, '', 'Zucchini', 'obst', { x: 'mittelgroß' }),
      I(250, 'g', 'Ricotta', 'kuehl'),
      I(40, 'g', 'Parmesan', 'kuehl', { x: 'am Stück' }),
      I(1, '', 'Ei', 'kuehl', { pl: 'Eier' }),
      I(1, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(1, '', 'Bio-Zitrone', 'obst', { pl: 'Bio-Zitronen', x: 'Abrieb' }),
      I(1, 'Topf', 'Basilikum', 'obst', { x: 'oder Petersilie' }),
      I(150, 'g', 'Kirschtomaten', 'obst'),
      I(2, 'EL', 'Semmelbrösel', 'trocken'),
      I(1, '', 'Baguette', 'brot', { pl: 'Baguettes', x: 'zum Servieren' }),
      P(1, 'EL', 'Olivenöl'),
      P(null, '', 'Salz, Pfeffer & Chiliflocken'),
    ],
    steps: [
      'Zucchini längs halbieren und mit einem Teelöffel aushöhlen, dabei einen 1 cm breiten Rand lassen. Das Fruchtfleisch beiseitestellen.',
      [TMX('Parmesan & Kräuter', 10, null, 10), 'Parmesan in Stücken, Knoblauch und ein paar Kräuterblättchen in den Mixtopf geben und fein zerkleinern. Die Hälfte davon für die Kruste herausnehmen.'],
      [TMX('Füllung rühren', 15, null, 4), 'Zucchinifleisch, Ricotta, Ei, Zitronenabrieb, Salz und Pfeffer zugeben und zu einer Füllung verrühren.'],
      'Zucchinihälften innen leicht salzen, mit Öl bepinseln und die Füllung einfüllen. Semmelbrösel mit der beiseitegestellten Parmesanmischung mischen und darüberstreuen.',
      [A('Zucchini überbacken', 180, 15), 'Zucchini nebeneinander in den Korb setzen (bei kleinem Korb in zwei Durchgängen) und garen, bis die Füllung gestockt und die Kruste goldbraun ist. Die Kirschtomaten in den letzten 5 Min dazulegen.'],
      'Mit frischen Kräutern, einem Spritzer Zitrone und Baguette servieren.',
    ],
    tip: 'Übrige Ricottamasse schmeckt auch als Füllung für Paprika oder Champignons.' },

  { id: 'quinoa', t: 'Quinoa', pen: 'script', cat: 'haupt', name: 'Quinoa-Bowl mit Röstgemüse & Joghurt-Dressing', time: 35,
    ing: [
      I(150, 'g', 'Quinoa', 'trocken'),
      I(1, '', 'Süßkartoffel', 'obst', { pl: 'Süßkartoffeln', x: 'ca. 400 g' }),
      I(1, 'Dose', 'Kichererbsen', 'konserve', { x: '400 g' }),
      I(1, '', 'Avocado', 'obst', { pl: 'Avocados' }),
      I(100, 'g', 'Babyspinat', 'obst'),
      I(150, 'g', 'Kirschtomaten', 'obst'),
      I(1, '', 'Zitrone', 'obst', { pl: 'Zitronen' }),
      I(150, 'g', 'Naturjoghurt', 'kuehl'),
      I(2, 'EL', 'Kürbiskerne', 'backen'),
      I(0.5, 'TL', 'Kreuzkümmel', 'gewuerz'),
      P(2, 'EL', 'Olivenöl'),
      P(1, 'TL', 'Paprikapulver', { x: 'gern geräuchert' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      [TMX('Quinoa garen', 18 * MIN, 100, 4), 'Quinoa im Garkörbchen gründlich abspülen. 1 Liter Wasser und 1 TL Salz in den Mixtopf geben, das Garkörbchen einhängen und die Quinoa garen, bis die Körner weich sind. Abtropfen lassen und mit einer Gabel auflockern.'],
      'Süßkartoffel schälen und in 2-cm-Würfel schneiden. Kichererbsen abgießen und gut trocken tupfen. Beides mit Öl, Paprikapulver, Kreuzkümmel und Salz mischen.',
      [A('Süßkartoffel & Kichererbsen rösten', 200, 18, 9), 'Süßkartoffel und Kichererbsen im Cosori rösten, nach 9 Min schütteln. Die Kichererbsen werden dabei schön knusprig.'],
      'Kürbiskerne in einer Pfanne ohne Fett rösten, bis sie springen.',
      'Joghurt mit Zitronensaft, Salz und Pfeffer zu einem Dressing verrühren (bei Bedarf mit 1–2 EL Wasser verdünnen).',
      'Quinoa auf Schalen verteilen. Spinat, halbierte Tomaten, Avocadoscheiben und das Röstgemüse darauf anrichten und mit Dressing und Kürbiskernen servieren.',
    ],
    tip: 'Gleich die doppelte Menge Quinoa kochen – sie hält sich drei Tage im Kühlschrank und passt in jeden Salat.' },

  { id: 'avocado', t: 'Avocado', pen: 'marker', cat: 'leicht', name: 'Avocado-Brot mit Ei aus dem Cosori', time: 20,
    ing: [
      I(4, 'Scheibe', 'Sauerteigbrot', 'brot', { x: 'oder Bauernbrot' }),
      I(2, '', 'reife Avocado', 'obst', { pl: 'reife Avocados' }),
      I(4, '', 'Ei', 'kuehl', { pl: 'Eier' }),
      I(1, '', 'Limette', 'obst', { pl: 'Limetten', x: 'oder ½ Zitrone' }),
      I(150, 'g', 'Kirschtomaten', 'obst'),
      I(1, '', 'Frühlingszwiebel', 'obst', { pl: 'Frühlingszwiebeln' }),
      I(1, 'Kästchen', 'Kresse', 'obst'),
      P(null, '', 'Salz, Pfeffer & Chiliflocken'),
    ],
    steps: [
      [A('Eier garen (wachsweich)', 130, 11), 'Die Eier direkt aus dem Kühlschrank in den Korb legen und im Cosori „kochen“: 9 Min für weiche, 11 Min für wachsweiche und 15 Min für harte Eier. Danach sofort in kaltes Wasser legen.'],
      [A('Brot rösten', 180, 4), 'Anschließend die Brotscheiben im Cosori knusprig rösten.'],
      'Avocados halbieren, entkernen und das Fruchtfleisch mit einer Gabel zerdrücken. Mit Limettensaft, Salz und Pfeffer abschmecken.',
      'Tomaten halbieren und die Frühlingszwiebel in Ringe schneiden. Eier pellen und halbieren.',
      'Brot dick mit Avocado bestreichen, mit Eiern, Tomaten und Frühlingszwiebel belegen und mit Kresse und Chiliflocken bestreuen.',
    ],
    tip: 'Die Eier-Zeiten schwanken je nach Gerät um ein bis zwei Minuten – beim ersten Mal ein Probe-Ei garen.' },

  { id: 'mozza', t: 'Mozza', pen: 'marker', cat: 'leicht', name: 'Tomate-Mozzarella mit Knoblauch-Ciabatta', time: 15,
    ing: [
      I(2, 'Kugel', 'Mozzarella', 'kuehl', { x: 'je 125 g, gern Büffelmozzarella' }),
      I(4, '', 'große Tomate', 'obst', { pl: 'große Tomaten', x: 'z. B. Ochsenherz' }),
      I(1, 'Topf', 'Basilikum', 'obst'),
      I(1, '', 'Ciabatta', 'brot'),
      I(1, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      P(4, 'EL', 'Olivenöl'),
      P(1, 'EL', 'Balsamico'),
      P(null, '', 'grobes Salz & Pfeffer'),
    ],
    steps: [
      'Tomaten und Mozzarella in Scheiben schneiden und abwechselnd auf einer Platte anrichten. Mit Salz und Pfeffer würzen.',
      'Ciabatta in fingerdicke Scheiben schneiden und mit 1 EL Olivenöl beträufeln.',
      [A('Ciabatta rösten', 190, 4, 2), 'Ciabatta im Cosori rösten, nach 2 Min wenden. Die warmen Scheiben mit der halbierten Knoblauchzehe einreiben.'],
      'Basilikumblätter über Tomaten und Mozzarella zupfen, mit dem restlichen Olivenöl und Balsamico beträufeln und mit dem warmen Ciabatta servieren.',
    ],
    tip: 'Am besten schmeckt es, wenn Tomaten und Mozzarella nicht direkt aus dem Kühlschrank kommen.' },

  { id: 'bananenshake', t: 'Bananen-Shake', pen: 'script', cat: 'suess', name: 'Bananen-Shake', time: 5,
    ing: [
      I(2, '', 'reife Banane', 'obst', { pl: 'reife Bananen' }),
      I(400, 'ml', 'Milch', 'kuehl', { x: 'kalt, oder Haferdrink' }),
      I(100, 'g', 'Naturjoghurt', 'kuehl'),
      P(1, 'TL', 'Honig', { s: 'backen' }),
      P(1, 'Prise', 'Zimt'),
    ],
    steps: [
      'Bananen schälen und in Stücke brechen.',
      [TMX('Pürieren', 30, null, 10), 'Mit Milch, Joghurt, Honig und Zimt in den Mixtopf geben und mit eingesetztem Messbecher fein pürieren.'],
      'Sofort in Gläser füllen und servieren.',
    ],
    tip: 'Besonders cremig wird der Shake mit gefrorenen Bananenstücken – reife Bananen dafür einfach geschält einfrieren.' },

  { id: 'milchreis', t: 'Milchreis + Zwetschgen', pen: 'script', cat: 'suess', name: 'Milchreis mit Cosori-Zwetschgen', time: 40,
    ing: [
      I(125, 'g', 'Milchreis', 'trocken'),
      I(500, 'ml', 'Milch', 'kuehl'),
      I(300, 'g', 'Zwetschgen', 'obst', { x: 'außerhalb der Saison TK' }),
      I(1, 'Pck', 'Vanillezucker', 'backen'),
      P(2, 'EL', 'Zucker', { s: 'backen' }),
      P(1, 'TL', 'Zimt'),
      P(1, 'EL', 'Butter', { s: 'kuehl' }),
      P(1, 'Prise', 'Salz'),
    ],
    steps: [
      [TMX('Milchreis garen', 35 * MIN, 90, 1, true), 'Milch, Milchreis, 1 EL Zucker, Vanillezucker und Salz in den Mixtopf geben und cremig garen. Danach 10 Min im Mixtopf nachquellen lassen.'],
      'Zwetschgen halbieren und entsteinen. In einer kleinen ofenfesten Form, die in den Korb passt, mit 1 EL Zucker, Zimt und Butterflöckchen mischen.',
      [A('Zwetschgen garen', 180, 10, 5), 'Zwetschgen im Cosori garen, bis sie weich sind und Saft ziehen. Nach 5 Min umrühren.'],
      'Milchreis in Schalen füllen und die warmen Zwetschgen samt Saft darauf geben.',
    ],
    tip: 'Im Winter klappt es genauso mit Apfelstücken oder TK-Kirschen.' },

  { id: 'fenchel', t: 'Fenchel Kichererbsen Ciabatta', pen: 'script', cat: 'haupt', name: 'Ofenfenchel mit knusprigen Kichererbsen & Ciabatta', time: 35,
    ing: [
      I(2, '', 'Fenchelknolle', 'obst', { pl: 'Fenchelknollen' }),
      I(1, 'Dose', 'Kichererbsen', 'konserve', { x: '400 g' }),
      I(1, '', 'rote Zwiebel', 'obst', { pl: 'rote Zwiebeln' }),
      I(1, '', 'Bio-Zitrone', 'obst', { pl: 'Bio-Zitronen' }),
      I(100, 'g', 'Feta', 'kuehl'),
      I(1, 'Bund', 'Petersilie', 'obst'),
      I(1, '', 'Ciabatta', 'brot'),
      P(3, 'EL', 'Olivenöl'),
      P(1, 'TL', 'Paprikapulver'),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Fenchel putzen und das Grün beiseitelegen. Die Knollen in schmale Spalten schneiden – der Strunk hält sie zusammen. Zwiebel in Spalten schneiden.',
      'Kichererbsen abgießen, abspülen und gründlich trocken tupfen.',
      'Fenchel, Zwiebel und Kichererbsen mit 2 EL Öl, Paprikapulver, Salz und Pfeffer mischen.',
      [A('Fenchel & Kichererbsen rösten', 190, 18, [6, 12]), 'Im Cosori rösten und alle 6 Min schütteln, bis der Fenchel weich und an den Rändern gebräunt ist.'],
      [A('Ciabatta rösten', 190, 3), 'Ciabatta in Scheiben schneiden, mit etwas Öl beträufeln und zum Schluss kurz im Cosori rösten.'],
      'Zitronenabrieb und -saft, restliches Öl, gehackte Petersilie und Fenchelgrün darübergeben und den Feta darüberbröseln. Mit dem Ciabatta servieren.',
    ],
    tip: 'Ein Klecks Joghurt mit Zitrone und Knoblauch macht das Gericht noch runder.' },

  { id: 'caponata', t: 'Caponata', b: 'B', pen: 'script', cat: 'haupt', name: 'Caponata – sizilianisches Auberginengemüse', time: 45,
    ing: [
      I(2, '', 'Aubergine', 'obst', { pl: 'Auberginen', x: 'ca. 600 g' }),
      I(1, '', 'Zwiebel', 'obst', { pl: 'Zwiebeln' }),
      I(2, 'Stange', 'Staudensellerie', 'obst'),
      I(1, 'Dose', 'stückige Tomaten', 'konserve', { x: '400 g' }),
      I(2, 'EL', 'Kapern', 'konserve'),
      I(50, 'g', 'grüne Oliven', 'konserve', { x: 'entsteint' }),
      I(2, 'EL', 'Pinienkerne', 'backen'),
      I(1, 'Topf', 'Basilikum', 'obst'),
      I(1, '', 'Ciabatta', 'brot', { x: 'oder Baguette' }),
      P(3, 'EL', 'Olivenöl'),
      P(3, 'EL', 'Essig', { x: 'Weißwein- oder Rotweinessig' }),
      P(1, 'EL', 'Zucker', { s: 'backen' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Auberginen in 2-cm-Würfel schneiden und mit 2 EL Olivenöl und etwas Salz mischen.',
      [A('Auberginen rösten', 200, 15, 7), 'Auberginen im Cosori goldbraun rösten, nach 7 Min schütteln. Das ersetzt das klassische Frittieren in viel Öl.'],
      [TMX('Zerkleinern', 4, null, 5), 'Zwiebel halbieren, Sellerie in Stücke schneiden, beides in den Mixtopf geben und zerkleinern. Mit dem Spatel nach unten schieben.'],
      [TMX('Andünsten', 5 * MIN, 120, 1), 'Das restliche Öl zugeben und glasig dünsten.'],
      [TMX('Sauce köcheln', 10 * MIN, 100, 1, true), 'Tomaten, Kapern und halbierte Oliven zugeben und köcheln lassen. Das Garkörbchen statt des Messbechers auf den Deckel stellen.'],
      [TMX('Ziehen lassen', 5 * MIN, 90, 'sanft', true), 'Essig, Zucker und die gerösteten Auberginen zugeben und ziehen lassen. Mit Salz und Pfeffer süß-sauer abschmecken.'],
      'Pinienkerne in einer Pfanne ohne Fett rösten. Caponata lauwarm mit Basilikum, Pinienkernen und frischem Brot servieren.',
    ],
    tip: 'Caponata schmeckt am nächsten Tag noch besser – ideal zum Vorkochen.' },

  { id: 'sellerie', t: 'Staudensellerie-Salat', b: 'B', pen: 'script', cat: 'leicht', name: 'Staudensellerie-Salat mit Apfel & Walnüssen', time: 20,
    ing: [
      I(1, 'Bund', 'Staudensellerie', 'obst', { x: 'ca. 5 Stangen mit Grün' }),
      I(1, '', 'säuerlicher Apfel', 'obst', { pl: 'säuerliche Äpfel', x: 'z. B. Boskoop' }),
      I(50, 'g', 'Walnusskerne', 'backen'),
      I(30, 'g', 'Parmesan', 'kuehl', { x: 'am Stück' }),
      I(1, '', 'Zitrone', 'obst', { pl: 'Zitronen' }),
      I(2, 'Scheibe', 'Bauernbrot', 'brot', { x: 'dazu' }),
      P(3, 'EL', 'Olivenöl'),
      P(1, 'TL', 'Honig', { s: 'backen' }),
      P(1, 'TL', 'Senf'),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      [A('Walnüsse rösten', 160, 5, 2), 'Walnüsse im Cosori rösten, nach 2 Min schütteln. Gut aufpassen, Nüsse werden schnell zu dunkel. Abkühlen lassen und grob hacken.'],
      'Sellerie waschen und das zarte Grün beiseitelegen. Die Stangen schräg in feine Scheiben schneiden.',
      'Apfel vierteln, entkernen und in feine Stifte schneiden.',
      'Zitronensaft, Öl, Honig, Senf, Salz und Pfeffer zu einem Dressing verrühren.',
      'Sellerie und Apfel mit dem Dressing mischen und 5 Min ziehen lassen. Mit Walnüssen, Parmesanspänen (mit dem Sparschäler hobeln) und Selleriegrün servieren.',
    ],
    tip: 'Wer mag, gibt eine Handvoll Weintrauben oder ein paar Würfel Blauschimmelkäse dazu.' },

  { id: 'bohnen', t: 'Bohnen Spiegelei Wedges', pen: 'script', cat: 'haupt', name: 'Grüne Bohnen mit Spiegelei & Cosori-Wedges', time: 35,
    ing: [
      I(600, 'g', 'festkochende Kartoffeln', 'obst'),
      I(400, 'g', 'grüne Bohnen', 'obst'),
      I(1, '', 'Zwiebel', 'obst', { pl: 'Zwiebeln', x: 'oder Schalotte' }),
      I(4, '', 'Ei', 'kuehl', { pl: 'Eier' }),
      I(1, 'TL', 'Bohnenkraut', 'gewuerz', { x: 'getrocknet' }),
      P(2, 'EL', 'Rapsöl'),
      P(1, 'TL', 'Paprikapulver'),
      P(1, 'EL', 'Butter', { s: 'kuehl' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Kartoffeln gründlich waschen (die Schale bleibt dran) und in Spalten schneiden. Mit 1 EL Öl, Paprikapulver und Salz mischen.',
      [A('Wedges', 200, 22, [10, 20]), 'Wedges im Cosori goldbraun und knusprig garen, nach 10 und 20 Min schütteln. Den Korb höchstens zur Hälfte füllen.'],
      [TMX('Bohnen dämpfen', 20 * MIN, 'varoma', 1), 'Bohnen putzen und in den Varoma legen. 500 g Wasser in den Mixtopf geben, den Varoma aufsetzen und die Bohnen bissfest dämpfen. Dünne Bohnen schon nach 15 Min probieren.'],
      'Zwiebel fein würfeln und in einer Pfanne in der Butter glasig dünsten. Die Bohnen mit dem Bohnenkraut darin schwenken, salzen und pfeffern.',
      'Die Eier in einer Pfanne mit dem restlichen Öl als Spiegeleier braten.',
      'Wedges, Bohnen und Spiegeleier zusammen anrichten.',
    ],
    tip: 'Dazu passt ein Klecks Kräuterquark.' },

  { id: 'handkaese', t: 'Handkäse mit Musik', note: 'Rote Beete', b: 'A', pen: 'marker', cat: 'leicht', name: 'Handkäse mit Musik & Röst-Rote-Beete', time: 45,
    ing: [
      I(200, 'g', 'Handkäse', 'kuehl', { x: '1 Packung' }),
      I(2, '', 'Zwiebel', 'obst', { pl: 'Zwiebeln' }),
      I(400, 'g', 'Rote Beete', 'obst', { x: 'roh, ca. 3 Knollen' }),
      I(4, 'Scheibe', 'Bauernbrot', 'brot'),
      I(1, 'TL', 'Kümmel', 'gewuerz', { x: 'ganz' }),
      P(5, 'EL', 'Apfelessig'),
      P(4, 'EL', 'Rapsöl'),
      P(1, 'TL', 'Honig', { s: 'backen' }),
      P(2, 'EL', 'Butter', { s: 'kuehl' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      [TMX('Zwiebeln zerkleinern', 4, null, 5), 'Zwiebeln halbieren, in den Mixtopf geben und fein zerkleinern.'],
      [TMX('Musik rühren', 10, null, 3, true), '4 EL Essig, 3 EL Wasser, 3 EL Öl, Kümmel und Pfeffer zugeben und zur „Musik“ verrühren.'],
      'Handkäse in eine flache Schale legen, mit der Marinade übergießen und abgedeckt mindestens 1 Std., besser über Nacht, im Kühlschrank ziehen lassen.',
      'Rote Beete schälen (am besten mit Handschuhen) und in Spalten schneiden. Mit 1 EL Öl und etwas Salz mischen.',
      [A('Rote Beete rösten', 200, 25, 12), 'Rote Beete im Cosori rösten, nach 12 Min schütteln. Noch warm mit Honig und 1 EL Essig marinieren.'],
      'Handkäse mit Musik mit Bauernbrot, Butter und der lauwarmen Roten Beete servieren.',
    ],
    tip: 'Ganz klassisch gibt es dazu ein Glas Apfelwein. Und am Kümmel nicht sparen!' },

  { id: 'rucola', t: 'Rucola Rote Beete Karotten Feta', b: 'A', pen: 'script', cat: 'leicht', name: 'Rucola-Salat mit Röst-Rote-Beete, Karotten & Feta', time: 35,
    ing: [
      I(300, 'g', 'Rote Beete', 'obst', { x: 'roh, ca. 2 Knollen' }),
      I(300, 'g', 'Karotten', 'obst'),
      I(100, 'g', 'Rucola', 'obst'),
      I(150, 'g', 'Feta', 'kuehl'),
      I(40, 'g', 'Walnusskerne', 'backen', { x: 'oder Kürbiskerne' }),
      P(3, 'EL', 'Olivenöl'),
      P(2, 'EL', 'Balsamico'),
      P(1, 'TL', 'Honig', { s: 'backen' }),
      P(1, 'TL', 'Senf'),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      'Rote Beete schälen (am besten mit Handschuhen) und in Spalten schneiden, Karotten längs vierteln. Mit 1 EL Öl, Salz und Pfeffer mischen.',
      [A('Rote Beete & Karotten rösten', 200, 22, 10), 'Gemüse im Cosori rösten. Nach 10 Min schütteln und die Karotten mit dem Honig beträufeln.'],
      'Walnüsse grob hacken und in einer Pfanne ohne Fett kurz anrösten.',
      'Balsamico, restliches Öl, Senf, Salz und Pfeffer zu einem Dressing verrühren.',
      'Rucola auf Teller verteilen, das lauwarme Gemüse darauf geben, Feta darüberbröseln und mit Nüssen und Dressing servieren.',
    ],
    tip: 'Wenn es schnell gehen soll: vorgegarte Rote Beete nehmen und nur die Karotten rösten (200 °C, 15 Min).' },

  { id: 'brot', t: 'Brot', pen: 'caps', cat: 'leicht', name: 'Abendbrot mit Quarkbrötchen aus dem Cosori', time: 35,
    ing: [
      I(250, 'g', 'Magerquark', 'kuehl'),
      I(1, '', 'Ei', 'kuehl', { pl: 'Eier' }),
      I(1, 'Pck', 'Backpulver', 'backen'),
      I(2, 'EL', 'Kürbiskerne', 'backen', { x: 'oder Sonnenblumenkerne' }),
      I(150, 'g', 'Käse', 'kuehl', { x: 'in Scheiben' }),
      I(150, 'g', 'Frischkäse', 'kuehl'),
      I(1, 'Bund', 'Radieschen', 'obst'),
      I(0.5, '', 'Salatgurke', 'obst', { pl: 'Salatgurken' }),
      I(1, 'Bund', 'Schnittlauch', 'obst'),
      P(250, 'g', 'Mehl', { s: 'backen', x: 'Type 550 oder 405' }),
      P(1, 'TL', 'Salz'),
      P(null, '', 'Butter', { s: 'kuehl' }),
    ],
    steps: [
      [TMX('Verrühren', 10, null, 4), 'Quark, Ei und Salz in den Mixtopf geben und verrühren.'],
      [TMX('Teig kneten', 1 * MIN, null, 'knet'), 'Mehl und Backpulver zugeben und zu einem glatten, leicht klebrigen Teig verkneten.'],
      'Mit bemehlten Händen 6 Brötchen formen und oben kreuzweise einschneiden. Die Oberseite mit Wasser bepinseln und in die Kerne drücken.',
      [A('Quarkbrötchen backen', 160, 16), 'Brötchen mit Abstand auf ein Stück Backpapier in den Korb setzen (nicht mit Backpapier vorheizen) und backen, bis sie goldbraun sind und beim Klopfen hohl klingen.'],
      'Etwas abkühlen lassen. Währenddessen Radieschen und Gurke in Scheiben schneiden und den Schnittlauch hacken.',
      'Mit Butter, Käse, Frischkäse, Gemüse und Schnittlauch als Abendbrot servieren.',
    ],
    tip: 'Keine Zeit zum Backen? Brot oder Brötchen vom Vortag im Cosori bei 160 °C in 3–4 Min wieder knusprig aufbacken.' },

  { id: 'risotto', t: 'Risotto mit Spinat & Salat', pen: 'script', cat: 'haupt', name: 'Spinat-Risotto mit Röst-Tomaten & Salat', time: 35,
    ing: [
      I(160, 'g', 'Risottoreis', 'trocken', { x: 'z. B. Arborio' }),
      I(1, '', 'Schalotte', 'obst', { pl: 'Schalotten', x: 'oder kleine Zwiebel' }),
      I(1, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(100, 'ml', 'Weißwein', 'getraenke', { x: 'oder mehr Brühe' }),
      I(150, 'g', 'Babyspinat', 'obst'),
      I(40, 'g', 'Parmesan', 'kuehl', { x: 'am Stück' }),
      I(200, 'g', 'Kirschtomaten', 'obst'),
      I(2, 'EL', 'Pinienkerne', 'backen'),
      I(1, '', 'Bio-Zitrone', 'obst', { pl: 'Bio-Zitronen' }),
      I(100, 'g', 'Feldsalat', 'obst', { x: 'oder Blattsalat' }),
      P(400, 'ml', 'Gemüsebrühe'),
      P(3, 'EL', 'Olivenöl'),
      P(1, 'EL', 'Balsamico'),
      P(1, 'EL', 'Butter', { s: 'kuehl' }),
      P(null, '', 'Salz & Pfeffer'),
    ],
    steps: [
      [TMX('Parmesan reiben', 10, null, 10), 'Parmesan in Stücken in den Mixtopf geben, fein reiben und umfüllen.'],
      [TMX('Zerkleinern', 3, null, 5), 'Schalotte und Knoblauch in den Mixtopf geben und zerkleinern. Mit dem Spatel nach unten schieben.'],
      [TMX('Andünsten', 3 * MIN, 120, 1), '1 EL Öl zugeben und andünsten.'],
      [TMX('Reis anschwitzen', 2 * MIN, 120, 1, true), 'Den Reis zugeben und anschwitzen.'],
      [TMX('Risotto garen', 14 * MIN, 100, 1, true), 'Weißwein und Brühe zugeben und garen, bis der Reis cremig ist, aber noch Biss hat. Das Garkörbchen statt des Messbechers auf den Deckel stellen.'],
      [A('Kirschtomaten schmoren', 190, 8), 'Währenddessen die Kirschtomaten mit 1 TL Öl und etwas Salz mischen und im Cosori schmoren, bis sie aufplatzen.'],
      'Pinienkerne in einer Pfanne ohne Fett goldbraun rösten.',
      'Das Risotto in eine große Schüssel füllen. Spinat, Butter und Parmesan unterheben – der Spinat fällt in der Hitze zusammen. Mit Salz, Pfeffer und etwas Zitronenabrieb abschmecken und 2 Min ruhen lassen.',
      'Salat mit dem restlichen Öl, Balsamico, Salz und Pfeffer anmachen. Risotto mit Röst-Tomaten, Pinienkernen und dem Salat servieren.',
    ],
    tip: 'Das Risotto soll cremig fließen wie eine kleine Welle. Lieber noch einen Schluck Brühe dazugeben.' },

  { id: 'zitronenpasta', t: 'Zitronenpasta mit Kapern & Salat', pen: 'script', cat: 'haupt', name: 'Zitronenpasta mit knusprigen Kapern & Salat', time: 25,
    ing: [
      I(250, 'g', 'Spaghetti', 'trocken', { x: 'oder Linguine' }),
      I(2, '', 'Bio-Zitrone', 'obst', { pl: 'Bio-Zitronen' }),
      I(2, 'EL', 'Kapern', 'konserve'),
      I(30, 'g', 'Semmelbrösel', 'trocken', { x: 'gern Panko' }),
      I(1, '', 'Knoblauchzehe', 'obst', { pl: 'Knoblauchzehen' }),
      I(50, 'g', 'Parmesan', 'kuehl', { x: 'am Stück' }),
      I(1, 'Bund', 'Petersilie', 'obst'),
      I(100, 'g', 'Rucola', 'obst', { x: 'oder Feldsalat' }),
      P(3, 'EL', 'Olivenöl'),
      P(40, 'g', 'Butter', { s: 'kuehl' }),
      P(null, '', 'Salz, Pfeffer & Chiliflocken'),
    ],
    steps: [
      'Kapern gut abtropfen lassen und trocken tupfen. Semmelbrösel mit 1 EL Olivenöl und dem fein gehackten Knoblauch mischen.',
      [A('Kapern & Brösel rösten', 180, 6, 3), 'Kapern und Brösel in zwei kleinen ofenfesten Schälchen in den Korb stellen und knusprig rösten, nach 3 Min umrühren.'],
      [TMX('Parmesan reiben', 10, null, 10), 'Parmesan in Stücken in den Mixtopf geben, fein reiben und umfüllen.'],
      [TMX('Petersilie hacken', 3, null, 8), 'Die Petersilienblättchen in den Mixtopf geben und hacken.'],
      'Pasta in reichlich Salzwasser al dente kochen. Vor dem Abgießen eine Tasse Nudelwasser abschöpfen.',
      'Den Abrieb beider Zitronen und den Saft einer Zitrone mit Butter und geriebenem Parmesan im warmen Nudeltopf verrühren. Pasta und 4–6 EL Nudelwasser zugeben und kräftig schwenken, bis eine cremige Sauce entsteht.',
      'Mit Salz, Pfeffer und Chili abschmecken und mit Petersilie, knusprigen Kapern und Zitronenbröseln servieren.',
      'Den Salat mit dem restlichen Olivenöl, etwas Zitronensaft und Salz anmachen.',
    ],
    tip: 'Knusprige Kapern sind auch ein tolles Topping für Salate und Fisch.' },
];

/* tablecloth color, vegetarian flag and the Chefkoch search words for each dish */
const DISH_META = {
  joghurt: { tint: 'sky', veg: true, ck: 'Granola Joghurt' },
  bircher: { tint: 'berry', veg: true, ck: 'Bircher Müsli' },
  porridge: { tint: 'oat', veg: true, ck: 'Porridge Apfel Zimt' },
  linsen: { tint: 'butter', veg: false, ck: 'Linsen mit Spätzle' },
  tikka: { tint: 'apricot', veg: false, ck: 'Chicken Tikka Masala' },
  asianudeln: { tint: 'mint', veg: true, ck: 'gebratene Nudeln Tofu' },
  bolo: { tint: 'rose', veg: false, ck: 'Spaghetti Bolognese' },
  pizza: { tint: 'butter', veg: true, ck: 'Pizza Airfryer' },
  brotsalat: { tint: 'rose', veg: true, ck: 'Brotsalat Panzanella' },
  fisch: { tint: 'sky', veg: false, ck: 'Lachs Ofenkartoffeln' },
  ricotta: { tint: 'sage', veg: true, ck: 'gefüllte Zucchini Ricotta' },
  quinoa: { tint: 'apricot', veg: true, ck: 'Quinoa Bowl' },
  avocado: { tint: 'sage', veg: true, ck: 'Avocado Brot Ei' },
  mozza: { tint: 'mint', veg: true, ck: 'Tomate Mozzarella' },
  bananenshake: { tint: 'butter', veg: true, ck: 'Bananenshake' },
  milchreis: { tint: 'lilac', veg: true, ck: 'Milchreis Zwetschgen' },
  fenchel: { tint: 'mint', veg: true, ck: 'Fenchel Kichererbsen' },
  caponata: { tint: 'lilac', veg: true, ck: 'Caponata' },
  sellerie: { tint: 'oat', veg: true, ck: 'Staudensellerie Salat Apfel' },
  bohnen: { tint: 'sky', veg: true, ck: 'grüne Bohnen Spiegelei' },
  handkaese: { tint: 'berry', veg: true, ck: 'Handkäse mit Musik' },
  rucola: { tint: 'lilac', veg: true, ck: 'Rucola Rote Bete Feta' },
  brot: { tint: 'apricot', veg: true, ck: 'Quarkbrötchen Airfryer' },
  risotto: { tint: 'sage', veg: true, ck: 'Spinatrisotto' },
  zitronenpasta: { tint: 'butter', veg: true, ck: 'Zitronenpasta Kapern' },
};

const COSORI_RULES = [
  'Den Korb höchstens zur Hälfte bis zu zwei Dritteln füllen, damit die heiße Luft zirkulieren kann.',
  'Zur angegebenen Zeit schütteln oder wenden – der Timer erinnert euch daran.',
  'Backpapier nur mit Essen darauf in den Korb legen und nie beim Vorheizen: Es kann sonst an die Heizspirale fliegen.',
  'Ein Hauch Öl mit Pinsel oder Pumpsprüher macht Gemüse und Kartoffeln knusprig. Kein Antihaft-Spray mit Treibgas verwenden, es greift die Beschichtung an.',
  'Die Zeiten gelten für einen Korb mit etwa 5,5 Litern. Bei kleineren Modellen in Portionen garen und die letzten Minuten einmal nachsehen.',
  'Vorheizen lohnt sich bei Fleisch, Fisch und Pizza. Gemüse und Nüsse können direkt starten.',
  'Alle Rezepte bleiben bei höchstens 200 °C, das schafft jedes Cosori-Modell.',
];
const TM_RULES = [
  'Zwiebeln, Knoblauch und Gemüse halbiert oder in groben Stücken in den Mixtopf geben, 3–5 Sek/Stufe 5 zerkleinern und mit dem Spatel nach unten schieben.',
  'Angedünstet wird beim TM5, TM6 und TM7 mit 120 °C auf Stufe 1. Der ältere TM31 schafft nur 100 °C – dort zum Andünsten die Varoma-Temperatur wählen.',
  'Linkslauf schont alles, was stückig bleiben soll: Fleisch, Reis, Linsen und Gemüsestücke.',
  'Zum Einkochen das Garkörbchen statt des Messbechers auf den Deckel stellen – so entweicht Dampf, ohne dass es spritzt.',
  'Beim Pürieren heißer Speisen immer den Messbecher einsetzen.',
  'Der Mixtopf fasst höchstens 2,2 Liter. Für mehr Personen in zwei Durchgängen kochen.',
  'Zum Dampfgaren im Varoma mindestens 500 g Wasser in den Mixtopf geben – das reicht für etwa 30 Minuten.',
];

/* the week as it hangs on the fridge – used only for a device without shared storage */
const STARTER = {
  mo: { f: ['joghurt'], h: [] }, di: { f: ['joghurt'], h: [] }, mi: { f: ['bircher'], h: [] },
  do: { f: ['porridge'], h: [] }, fr: { f: ['bircher'], h: [] }, sa: { f: ['porridge'], h: ['linsen'] },
  so: { f: ['joghurt'], h: [] },
};

